### ISSUE TITLE
Add a page to represent IRC Channel

### ISSUE THREAD

**Issue by joshfinnie** [NodeDC/node.dc#24]
We have a wonderful API from @adunkman found [here](https://github.com/NodeDC/node-dc-irc)... we want this to be available on the NodeDC website.

- [ ] Make a node.js API consumer
- [ ] Make an angular.js controller
- [ ] Make a nice template

**Comment by jkeam** [comment]
Implemented in https://github.com/NodeDC/node.dc/pull/26.

**Comment by adunkman** [comment]
Boom!
